public with sharing class IManageWFolder {
    public Datetime  activity_date { get; set; }

    public String container_saved_search_id { get; set; }

    public String content_saved_search_id { get; set; }

    public String database { get; set; }

    public String default_security { get; set; }

    public String description { get; set; }

    public Datetime edit_date { get; set; }

    public String effective_security { get; set; }

    public String email { get; set; }

    public String folder_type { get; set; }

    public Boolean has_documents { get; set; }

    public Boolean has_security { get; set; }

    public Boolean has_subfolders { get; set; }

    public String id { get; set; }

    public String imanage_share_eid { get; set; }

    public String imanage_share_url { get; set; }

    public String inherited_default_security { get; set; }

    public Boolean is_container_saved_search { get; set; }

    public Boolean is_content_saved_search { get; set; }

    public Boolean is_external { get; set; }

    public Boolean is_external_as_normal { get; set; }

    public String location { get; set; }

    public String my_matters_shortcut_id { get; set; }

    public String name { get; set; }

    public String owner { get; set; }

    public String owner_description { get; set; }

    public String parent_id { get; set; }

    //public WFolderProfile profile { get; set; }

    //public WSearchFolderProfile searchprofile { get; set; }

    public String project_custom1 { get; set; }

    public String project_custom2 { get; set; }

    public String project_custom3 { get; set; }

    public String security_policy { get; set; }

    public String subtype { get; set; }

    public String view_type { get; set; }

    public String workspace_id { get; set; }

    public String workspace_name { get; set; }

    public String wstype { get; set; }
}