public abstract with sharing class IManageWCustomFieldsWithDesc extends IManageWCustomFields {
    public String custom1_description { get; set; }
    public String custom2_description { get; set; }
    public String custom3_description { get; set; }
    public String custom4_description { get; set; }
    public String custom5_description { get; set; }
    public String custom6_description { get; set; }
    public String custom7_description { get; set; }
    public String custom8_description { get; set; }
    public String custom9_description { get; set; }
    public String custom10_description { get; set; }
    public String custom11_description { get; set; }
    public String custom12_description { get; set; }
    public String custom29_description { get; set; }
    public String custom30_description { get; set; }
    public String custom31_description { get; set; }
}