public abstract with sharing class IManageWCustomFieldsWithDesc extends IManageWCustomFields {
    public String custom1Description { get; set; }
    public String custom2Description { get; set; }
    public String custom3Description { get; set; }
    public String custom4Description { get; set; }
    public String custom5Description { get; set; }
    public String custom6Description { get; set; }
    public String custom7Description { get; set; }
    public String custom8Description { get; set; }
    public String custom9Description { get; set; }
    public String custom10Description { get; set; }
    public String custom11Description { get; set; }
    public String custom12Description { get; set; }
    public String custom29Description { get; set; }
    public String custom30Description { get; set; }
    public String custom31Description { get; set; }
}