public with sharing class IManageMapping {
  @AuraEnabled
  public String EntityType;
  @AuraEnabled
  public String EntityMatterIdObjectField;
  @AuraEnabled
  public String MatterIdField;
  @AuraEnabled
  public String MatterNameField;
  @AuraEnabled
  public String EntityClientIdObjectField;
  @AuraEnabled
  public String ClientIdField;
  @AuraEnabled
  public String ClientNameField;
  @AuraEnabled
  public String WsTemplateField;
  @AuraEnabled
  public String LibraryField;
  @AuraEnabled
  public Boolean UseOnlyCustom2;
}
